from __future__ import annotations

import re
import unicodedata
from typing import Final, TypedDict


class LanguageInfo(TypedDict):
    code: str
    name: str
    native_name: str


LANGUAGE_ENDONYMS: Final[dict[str, str]] = {
    'aa': 'Afar',
    'ab': 'Аԥсшәа',
    'ae': 'Avestan',
    'af': 'Afrikaans',
    'ak': 'Akan',
    'am': 'አማርኛ',
    'an': 'aragonés',
    'ar': 'العربية',
    'as': 'অসমীয়া',
    'av': 'Avaric',
    'ay': 'Aymara',
    'az': 'azərbaycan',
    'ba': 'башҡорт теле',
    'be': 'беларуская',
    'bg': 'български',
    'bh': 'भोजपुरी',
    'bi': 'Bislama',
    'bm': 'bamanakan',
    'bn': 'বাংলা',
    'bo': 'བོད་སྐད་',
    'br': 'brezhoneg',
    'bs': 'bosanski',
    'ca': 'català',
    'ce': 'нохчийн',
    'ch': 'Chamorro',
    'co': 'corsu',
    'cr': 'Cree',
    'cs': 'čeština',
    'cu': 'Church Slavic',
    'cv': 'чӑваш',
    'cy': 'Cymraeg',
    'da': 'dansk',
    'de': 'Deutsch',
    'dv': 'Divehi',
    'dz': 'རྫོང་ཁ',
    'ee': 'eʋegbe',
    'el': 'Ελληνικά',
    'en': 'English',
    'eo': 'Esperanto',
    'es': 'español',
    'et': 'eesti',
    'eu': 'euskara',
    'fa': 'فارسی',
    'ff': 'Pulaar',
    'fi': 'suomi',
    'fj': 'Fijian',
    'fo': 'føroyskt',
    'fr': 'français',
    'fy': 'Frysk',
    'ga': 'Gaeilge',
    'gd': 'Gàidhlig',
    'gl': 'galego',
    'gn': 'avañe’ẽ',
    'gu': 'ગુજરાતી',
    'gv': 'Gaelg',
    'ha': 'Hausa',
    'he': 'עברית',
    'hi': 'हिन्दी',
    'ho': 'Hiri Motu',
    'hr': 'hrvatski',
    'ht': 'Kreyòl Ayisyen',
    'hu': 'magyar',
    'hy': 'հայերեն',
    'hz': 'Herero',
    'ia': 'interlingua',
    'id': 'bahasa Indonesia',
    'ie': 'Interlingue',
    'ig': 'Igbo',
    'ii': 'ꆈꌠꉙ',
    'ik': 'Inupiaq',
    'io': 'Ido',
    'is': 'íslenska',
    'it': 'italiano',
    'iu': 'Inuktitut',
    'ja': '日本語',
    'jv': 'Jawa',
    'ka': 'ქართული',
    'kg': 'Kongo',
    'ki': 'Gikuyu',
    'kj': 'Kuanyama',
    'kk': 'қазақ тілі',
    'kl': 'kalaallisut',
    'km': 'ខ្មែរ',
    'kn': 'ಕನ್ನಡ',
    'ko': '한국어',
    'kr': 'Kanuri',
    'ks': 'کٲشُر',
    'ku': 'kurdî (kurmancî)',
    'kv': 'Komi',
    'kw': 'kernewek',
    'ky': 'кыргызча',
    'la': 'Lingua latina',
    'lb': 'Lëtzebuergesch',
    'lg': 'Luganda',
    'li': 'Limburgish',
    'ln': 'lingála',
    'lo': 'ລາວ',
    'lt': 'lietuvių',
    'lu': 'Tshiluba',
    'lv': 'latviešu',
    'mg': 'Malagasy',
    'mh': 'Marshallese',
    'mi': 'Māori',
    'mk': 'македонски',
    'ml': 'മലയാളം',
    'mn': 'монгол',
    'mr': 'मराठी',
    'ms': 'bahasa Malaysia',
    'mt': 'Malti',
    'my': 'မြန်မာ',
    'na': 'Nauru',
    'nb': 'norsk bokmål',
    'nd': 'isiNdebele',
    'ne': 'नेपाली',
    'ng': 'Ndonga',
    'nl': 'Nederlands',
    'nn': 'norsk nynorsk',
    'no': 'norsk',
    'nr': 'South Ndebele',
    'nv': 'Diné Bizaad',
    'ny': 'Nyanja',
    'oc': 'occitan',
    'oj': 'Ojibwa',
    'om': 'Oromoo',
    'or': 'ଓଡ଼ିଆ',
    'os': 'ирон',
    'pa': 'ਪੰਜਾਬੀ',
    'pi': 'Pali',
    'pl': 'polski',
    'ps': 'پښتو',
    'pt': 'português',
    'qu': 'Runasimi',
    'rm': 'rumantsch',
    'rn': 'Ikirundi',
    'ro': 'română',
    'ru': 'русский',
    'rw': 'Ikinyarwanda',
    'sa': 'संस्कृत भाषा',
    'sc': 'sardu',
    'sd': 'سنڌي',
    'se': 'davvisámegiella',
    'sg': 'Sängö',
    'si': 'සිංහල',
    'sk': 'slovenčina',
    'sl': 'slovenščina',
    'sm': 'Samoan',
    'sn': 'chiShona',
    'so': 'Soomaali',
    'sq': 'shqip',
    'sr': 'српски',
    'ss': 'siSwati',
    'st': 'Sesotho',
    'su': 'Basa Sunda',
    'sv': 'svenska',
    'sw': 'Kiswahili',
    'ta': 'தமிழ்',
    'te': 'తెలుగు',
    'tg': 'тоҷикӣ',
    'th': 'ไทย',
    'ti': 'ትግርኛ',
    'tk': 'türkmen dili',
    'tl': 'Filipino',
    'tn': 'Setswana',
    'to': 'lea fakatonga',
    'tr': 'Türkçe',
    'ts': 'Tsonga',
    'tt': 'татар',
    'tw': 'Akan',
    'ty': 'Tahitian',
    'ug': 'ئۇيغۇرچە',
    'uk': 'українська',
    'ur': 'اردو',
    'uz': 'o‘zbek',
    've': 'tshiVenḓa',
    'vi': 'Tiếng Việt',
    'vo': 'Volapük',
    'wa': 'walon',
    'wo': 'Wolof',
    'xh': 'IsiXhosa',
    'yi': 'ייִדיש',
    'yo': 'Èdè Yorùbá',
    'za': 'Vahcuengh',
    'zh': '中文',
    'zu': 'isiZulu',
}

LANGUAGE_NAMES: Final[dict[str, str]] = {
    'aa': 'Afar',
    'ab': 'Abkhazian',
    'ae': 'Avestan',
    'af': 'Afrikaans',
    'ak': 'Akan',
    'am': 'Amharic',
    'an': 'Aragonese',
    'ar': 'Arabic',
    'as': 'Assamese',
    'av': 'Avaric',
    'ay': 'Aymara',
    'az': 'Azerbaijani',
    'ba': 'Bashkir',
    'be': 'Belarusian',
    'bg': 'Bulgarian',
    'bh': 'Bihari languages',
    'bi': 'Bislama',
    'bm': 'Bambara',
    'bn': 'Bangla',
    'bo': 'Tibetan',
    'br': 'Breton',
    'bs': 'Bosnian',
    'ca': 'Catalan',
    'ce': 'Chechen',
    'ch': 'Chamorro',
    'co': 'Corsican',
    'cr': 'Cree',
    'cs': 'Czech',
    'cu': 'Church Slavic',
    'cv': 'Chuvash',
    'cy': 'Welsh',
    'da': 'Danish',
    'de': 'German',
    'dv': 'Divehi',
    'dz': 'Dzongkha',
    'ee': 'Ewe',
    'el': 'Greek',
    'en': 'English',
    'eo': 'Esperanto',
    'es': 'Spanish',
    'et': 'Estonian',
    'eu': 'Basque',
    'fa': 'Persian',
    'ff': 'Fula',
    'fi': 'Finnish',
    'fj': 'Fijian',
    'fo': 'Faroese',
    'fr': 'French',
    'fy': 'Western Frisian',
    'ga': 'Irish',
    'gd': 'Scottish Gaelic',
    'gl': 'Galician',
    'gn': 'Guarani',
    'gu': 'Gujarati',
    'gv': 'Manx',
    'ha': 'Hausa',
    'he': 'Hebrew',
    'hi': 'Hindi',
    'ho': 'Hiri Motu',
    'hr': 'Croatian',
    'ht': 'Haitian Creole',
    'hu': 'Hungarian',
    'hy': 'Armenian',
    'hz': 'Herero',
    'ia': 'Interlingua',
    'id': 'Indonesian',
    'ie': 'Interlingue',
    'ig': 'Igbo',
    'ii': 'Sichuan Yi',
    'ik': 'Inupiaq',
    'io': 'Ido',
    'is': 'Icelandic',
    'it': 'Italian',
    'iu': 'Inuktitut',
    'ja': 'Japanese',
    'jv': 'Javanese',
    'ka': 'Georgian',
    'kg': 'Kongo',
    'ki': 'Kikuyu',
    'kj': 'Kuanyama',
    'kk': 'Kazakh',
    'kl': 'Kalaallisut',
    'km': 'Khmer',
    'kn': 'Kannada',
    'ko': 'Korean',
    'kr': 'Kanuri',
    'ks': 'Kashmiri',
    'ku': 'Kurdish',
    'kv': 'Komi',
    'kw': 'Cornish',
    'ky': 'Kyrgyz',
    'la': 'Latin',
    'lb': 'Luxembourgish',
    'lg': 'Ganda',
    'li': 'Limburgish',
    'ln': 'Lingala',
    'lo': 'Lao',
    'lt': 'Lithuanian',
    'lu': 'Luba-Katanga',
    'lv': 'Latvian',
    'mg': 'Malagasy',
    'mh': 'Marshallese',
    'mi': 'Māori',
    'mk': 'Macedonian',
    'ml': 'Malayalam',
    'mn': 'Mongolian',
    'mr': 'Marathi',
    'ms': 'Malay',
    'mt': 'Maltese',
    'my': 'Burmese',
    'na': 'Nauru',
    'nb': 'Norwegian Bokmål',
    'nd': 'North Ndebele',
    'ne': 'Nepali',
    'ng': 'Ndonga',
    'nl': 'Dutch',
    'nn': 'Norwegian Nynorsk',
    'no': 'Norwegian',
    'nr': 'South Ndebele',
    'nv': 'Navajo',
    'ny': 'Nyanja',
    'oc': 'Occitan',
    'oj': 'Ojibwa',
    'om': 'Oromo',
    'or': 'Odia',
    'os': 'Ossetic',
    'pa': 'Punjabi',
    'pi': 'Pali',
    'pl': 'Polish',
    'ps': 'Pashto',
    'pt': 'Portuguese',
    'qu': 'Quechua',
    'rm': 'Romansh',
    'rn': 'Rundi',
    'ro': 'Romanian',
    'ru': 'Russian',
    'rw': 'Kinyarwanda',
    'sa': 'Sanskrit',
    'sc': 'Sardinian',
    'sd': 'Sindhi',
    'se': 'Northern Sami',
    'sg': 'Sango',
    'si': 'Sinhala',
    'sk': 'Slovak',
    'sl': 'Slovenian',
    'sm': 'Samoan',
    'sn': 'Shona',
    'so': 'Somali',
    'sq': 'Albanian',
    'sr': 'Serbian',
    'ss': 'Swati',
    'st': 'Southern Sotho',
    'su': 'Sundanese',
    'sv': 'Swedish',
    'sw': 'Swahili',
    'ta': 'Tamil',
    'te': 'Telugu',
    'tg': 'Tajik',
    'th': 'Thai',
    'ti': 'Tigrinya',
    'tk': 'Turkmen',
    'tl': 'Filipino',
    'tn': 'Tswana',
    'to': 'Tongan',
    'tr': 'Turkish',
    'ts': 'Tsonga',
    'tt': 'Tatar',
    'tw': 'Twi',
    'ty': 'Tahitian',
    'ug': 'Uyghur',
    'uk': 'Ukrainian',
    'ur': 'Urdu',
    'uz': 'Uzbek',
    've': 'Venda',
    'vi': 'Vietnamese',
    'vo': 'Volapük',
    'wa': 'Walloon',
    'wo': 'Wolof',
    'xh': 'Xhosa',
    'yi': 'Yiddish',
    'yo': 'Yoruba',
    'za': 'Zhuang',
    'zh': 'Chinese',
    'zu': 'Zulu',
}


def _normalize_text(value: str) -> str:
    normalized = unicodedata.normalize('NFKD', value.strip().casefold())
    without_diacritics = ''.join(
        character for character in normalized if not unicodedata.combining(character)
    )
    cleaned = re.sub(r"[^\w\s]", " ", without_diacritics, flags=re.UNICODE)
    return re.sub(r"\s+", " ", cleaned).strip()


def _build_name_index() -> dict[str, list[str]]:
    index: dict[str, list[str]] = {}
    for code in sorted(LANGUAGE_ENDONYMS):
        candidates = {code, LANGUAGE_NAMES[code], LANGUAGE_ENDONYMS[code]}
        for candidate in candidates:
            key = _normalize_text(candidate)
            if not key:
                continue
            index.setdefault(key, []).append(code)

    for codes in index.values():
        codes.sort()

    return index


NAME_TO_CODES: Final[dict[str, list[str]]] = _build_name_index()


def get_language_name(code: str) -> str | None:
    return LANGUAGE_ENDONYMS.get(code.strip().lower())


def get_language_display_name(code: str) -> str | None:
    return LANGUAGE_NAMES.get(code.strip().lower())


def get_language_code(name: str) -> str | None:
    matches = find_language_codes(name)
    return matches[0] if matches else None


def find_language_codes(name: str) -> list[str]:
    return NAME_TO_CODES.get(_normalize_text(name), []).copy()


def list_language_codes() -> list[str]:
    return sorted(LANGUAGE_ENDONYMS)


def list_language_names() -> list[str]:
    return [LANGUAGE_ENDONYMS[code] for code in list_language_codes()]


def list_language_display_names() -> list[str]:
    return [LANGUAGE_NAMES[code] for code in list_language_codes()]


def list_languages() -> list[LanguageInfo]:
    return [
        {
            'code': code,
            'name': LANGUAGE_NAMES[code],
            'native_name': LANGUAGE_ENDONYMS[code],
        }
        for code in list_language_codes()
    ]


def is_supported_language_code(code: str) -> bool:
    return code.strip().lower() in LANGUAGE_ENDONYMS


__all__ = [
    'LANGUAGE_ENDONYMS',
    'LANGUAGE_NAMES',
    'NAME_TO_CODES',
    'LanguageInfo',
    'find_language_codes',
    'get_language_code',
    'get_language_display_name',
    'get_language_name',
    'is_supported_language_code',
    'list_language_codes',
    'list_language_display_names',
    'list_language_names',
    'list_languages',
]
